project_id = "tzcvqppdgugdfbhujbvc"

[functions.analyze-resume]
verify_jwt = true

[functions.fetch-jobs]
verify_jwt = true

[functions.match-jobs]
verify_jwt = true

[functions.send-notification]
verify_jwt = true
